name: Config Filter
type: module
description: Config Filter allows other modules to inteact with a ConfigStorage through filter plugins.
# core: 8.x
package: Config

# Information added by Drupal.org packaging script on 2017-03-09
version: '8.x-1.0-beta3'
core: '8.x'
project: 'config_filter'
datestamp: 1489063684
