sudo: required
language: php
dist: trusty
php:
  - 5.6
matrix:
  fast_finish: true
env:
  global:
    - COMPOSER_BIN=$TRAVIS_BUILD_DIR/vendor/bin
    - BLT_DIR=$TRAVIS_BUILD_DIR/vendor/acquia/blt
    - BUILD_DIR=$TRAVIS_BUILD_DIR
jdk:
  - oraclejdk8
cache:
  bundler: true
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache
    - $HOME/.npm
    - $HOME/.nvm
    - vendor
addons:
  ssh_known_hosts:
    - svn-5223.devcloud.hosting.acquia.com
notifications: null
before_install:
  - 'phpenv config-rm xdebug.ini'
  - 'composer self-update'
  - 'composer validate --no-check-all --ansi'
  - 'composer install'
install:
  - 'source ${BLT_DIR}/scripts/travis/setup_environment'
  - 'source $BLT_DIR/scripts/travis/setup_project'
script:
  - 'source $BLT_DIR/scripts/travis/run_tests'
deploy:
  -
    provider: script
    script: $BLT_DIR/scripts/travis/deploy_branch
    skip_cleanup: true
    'on': { branch: develop, php: 5.6 }
  -
    provider: script
    script: $BLT_DIR/scripts/travis/deploy_branch
    skip_cleanup: true
    'on': { branch: master, php: 5.6 }
  -
    provider: script
    script: $BLT_DIR/scripts/travis/deploy_tag
    skip_cleanup: true
    'on': { tags: true, php: 5.6 }
